length = int(input('Введите длину стороны квадрата: '))
print('\nВывод:')
print('Периметр: ', (length*4))
print('Площадь: ', (length**2))
length = int(input('\nВведите длину стороны прямоугольника: '))
width = int(input('Введите ширину стороны прямоугольника: '))
print('\nВывод:')
print('Периметр: ', (length*2+width*2))
print('Площадь: ', (length*width))